/** Typed mirror of the light theme. CSS in tokens.css is the source of truth
 *  for runtime; this map is for TS consumers (docs, inline styles, tests). */
export const tokens = {
  color: {
    accent: '#0E7C7C',
    'accent-hover': '#0B6A6A',
    'accent-active': '#085858',
    'bg-app': '#F0F0F0',
    surface: '#FFFFFF',
    'surface-subtle': '#F7F7F7',
    'section-bar': '#EBEBEB',
    border: '#D6D6D6',
    'border-strong': '#C2C2C2',
    'control-border': '#878787',
    'text-primary': '#262626',
    'text-secondary': '#666666',
    'text-muted': '#6B6B6B',
    'text-faint': '#757575',
    'text-disabled': '#B0B0B0',
    'text-on-accent': '#FFFFFF',
    'text-on-solid': '#FFFFFF',
    success: '#2A7030',
    warning: '#8A6600',
    error: '#BB2F28',
    info: '#2764AD',
    'success-fg': '#245F29',
    'warning-fg': '#755700',
    'error-fg': '#9F2822',
    'info-fg': '#215593',
    'table-header': '#F2F2F2',
    'table-zebra': '#F5F5F5',
    'table-selected': '#DCEFEF',
    'table-hover': '#F0F7F7',
    'table-grid': '#E4E4E4',
    'row-muted-fg': '#666666',
    'skel-base': '#D2D2D2',
    'skel-highlight': '#F2F2F2',
    weekend: '#BE4E1E',
    highlight: '#F5D060',
    'heat-0': '#E6E9E9',
    'heat-1': '#ADD3D3',
    'heat-2': '#7AB7B7',
    'heat-3': '#449A9A',
    'heat-4': '#0E7C7C',
    'chart-1': '#0B7979',
    'chart-2': '#9D7C12',
    'chart-3': '#830FFA',
    'chart-4': '#138EB7',
    'chart-5': '#C32739',
    'chart-6': '#42650C',
    'chart-7': '#4E5CC2',
    'chart-8': '#B65C8B',
  },
  font: { ui: 'Inter, "Segoe UI", Arial, sans-serif' },
  fontSize: {
    xs: 'calc(0.6875rem * var(--ds-ui-scale))',
    sm: 'calc(0.75rem * var(--ds-ui-scale))',
    base: 'calc(0.8125rem * var(--ds-ui-scale))',
    md: 'calc(0.875rem * var(--ds-ui-scale))',
    lg: 'calc(1rem * var(--ds-ui-scale))',
    xl: 'calc(1.25rem * var(--ds-ui-scale))',
    '2xl': 'calc(1.5rem * var(--ds-ui-scale))',
  },
  space: {
    1: 'calc(0.125rem * var(--ds-ui-scale))',
    2: 'calc(0.25rem * var(--ds-ui-scale))',
    3: 'calc(0.375rem * var(--ds-ui-scale))',
    4: 'calc(0.5rem * var(--ds-ui-scale))',
    5: 'calc(0.75rem * var(--ds-ui-scale))',
    6: 'calc(1rem * var(--ds-ui-scale))',
    7: 'calc(1.25rem * var(--ds-ui-scale))',
    8: 'calc(1.5rem * var(--ds-ui-scale))',
  },
  radius: { sm: '2px', base: '3px', md: '4px' },
  height: {
    compact: 'calc(1.75rem * var(--ds-ui-scale))',
    default: 'calc(2rem * var(--ds-ui-scale))',
    comfortable: 'calc(2.25rem * var(--ds-ui-scale))',
  },
  width: { colMin: 'calc(4rem * var(--ds-ui-scale))' },
  uiScale: 'var(--ds-ui-scale)',
} as const

export type ColorToken = keyof typeof tokens.color
/** `cssVar('accent')` -> `var(--ds-accent)` */
export const cssVar = (name: string) => `var(--ds-${name})`
